<a href="https://colab.research.google.com/github/robertmunro25/Practice1/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
a = np.array([1,2,3], dtype = 'int16')

In [3]:
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0,8.0,7.0], [3.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [3., 5., 4.]])

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape
b.shape

(2, 3)

In [9]:
a.dtype
b.dtype

dtype('float64')

In [13]:
a.itemsize

2

In [11]:
b.itemsize

8

In [14]:
a.size

3

In [15]:
b.size

6

In [16]:
b[1,1]

5.0

In [17]:
b[-1,-1]

4.0

In [19]:
b[:, 1]

array([8., 5.])

In [20]:
b[0, :]

array([9., 8., 7.])

In [21]:
b[1,2] = 20

In [22]:
b

array([[ 9.,  8.,  7.],
       [ 3.,  5., 20.]])

In [28]:
a = np.zeros((7,7))
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [30]:
b = np.ones((4,4,4))
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
np.full_like(b, 2)

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [36]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
np.random.rand(4,4,4)

array([[[0.88285243, 0.42117371, 0.83538461, 0.73011707],
        [0.35811897, 0.01492072, 0.20451285, 0.76552297],
        [0.39531377, 0.88938525, 0.61014097, 0.42720014],
        [0.4189683 , 0.62335083, 0.3194955 , 0.12668104]],

       [[0.71469488, 0.68364506, 0.37582983, 0.41111584],
        [0.80552368, 0.03140087, 0.18914884, 0.50972479],
        [0.32827666, 0.30841145, 0.71712704, 0.28151144],
        [0.55148212, 0.72709003, 0.72957935, 0.26166387]],

       [[0.25521278, 0.47174513, 0.07494295, 0.39638833],
        [0.55401996, 0.98169031, 0.22535881, 0.61501784],
        [0.61817499, 0.40906024, 0.65328342, 0.32045254],
        [0.10653593, 0.67368723, 0.61342956, 0.71272771]],

       [[0.08760094, 0.60400566, 0.45989902, 0.39836691],
        [0.44019258, 0.24824886, 0.22836491, 0.0989292 ],
        [0.92002443, 0.42811414, 0.37200518, 0.4009038 ],
        [0.73311302, 0.69947847, 0.15847342, 0.39047821]]])

In [43]:
c = np.random.rand(4,4,4)
c

array([[[0.0992067 , 0.37603487, 0.83897216, 0.32916435],
        [0.7518182 , 0.70791099, 0.25414085, 0.37424016],
        [0.96604829, 0.53688895, 0.41444638, 0.28974049],
        [0.88661366, 0.67336991, 0.60289672, 0.83487534]],

       [[0.95586575, 0.54160013, 0.00590825, 0.97325854],
        [0.0164914 , 0.55149498, 0.18595745, 0.16546881],
        [0.17778416, 0.83647234, 0.31164313, 0.27978374],
        [0.40373717, 0.08912397, 0.76494968, 0.65109195]],

       [[0.88086684, 0.16436152, 0.89760694, 0.25805895],
        [0.82051886, 0.12228992, 0.17927867, 0.63872174],
        [0.28949264, 0.06435475, 0.31896929, 0.27401613],
        [0.13902306, 0.89168161, 0.5924917 , 0.02166084]],

       [[0.98318061, 0.53818133, 0.29540588, 0.04123259],
        [0.75554079, 0.81032087, 0.06927441, 0.8788129 ],
        [0.66776251, 0.52707793, 0.48489626, 0.38438751],
        [0.5590852 , 0.59492053, 0.07771289, 0.27249259]]])

In [49]:
d = np.random.randint(10, size=(4,4,4))

In [50]:
d

array([[[3, 4, 4, 8],
        [8, 6, 4, 2],
        [9, 0, 4, 1],
        [0, 4, 8, 9]],

       [[1, 8, 5, 7],
        [9, 1, 1, 7],
        [2, 7, 6, 5],
        [9, 5, 3, 2]],

       [[3, 9, 6, 0],
        [5, 5, 3, 8],
        [3, 4, 0, 8],
        [8, 5, 7, 2]],

       [[7, 3, 7, 3],
        [7, 8, 6, 9],
        [1, 1, 0, 6],
        [7, 1, 9, 0]]])

In [52]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [55]:
r = np.ones((5,5))
r

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
r[1:4, 1:4] = 0

In [59]:
r

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
r[2,2] = 9

In [61]:
r

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
a = np.array([1,2,3])

In [63]:
b = a.copy()

In [64]:
b

array([1, 2, 3])

In [65]:
b[1] = 45

In [66]:
b

array([ 1, 45,  3])

In [67]:
a

array([1, 2, 3])

In [68]:
b - 23

array([-22,  22, -20])

In [69]:
b

array([ 1, 45,  3])

In [70]:
b = b -23

In [71]:
b

array([-22,  22, -20])

In [72]:
b += 23

In [73]:
b

array([ 1, 45,  3])

In [74]:
b **= 2

In [75]:
b

array([   1, 2025,    9])

In [76]:
c = np.identity(4)

In [77]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
stats = np.random.randint(10, size=(3,3))

In [80]:
stats

array([[7, 0, 2],
       [5, 2, 3],
       [4, 6, 8]])

In [81]:
np.min(stats)

0

In [82]:
np.max(stats)

8

In [83]:
np.mean(stats)

4.111111111111111

In [88]:
np.min(stats, axis=0)

array([4, 0, 2])

In [90]:
np.median(stats, axis=1)

array([2., 3., 6.])

In [96]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
np.vstack([before, before])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
np.hstack([before,before])

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [102]:
r

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
r > 1

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [104]:
r > 0

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [107]:
r[r>0]

array([1., 1., 1., 1., 1., 1., 1., 1., 9., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
r = 0

In [109]:
r

0